import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topheader from "./components/Topheader";
import MainHeader from "./components/MainHeader";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{

  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topheader />
         <MainHeader />
        {children}
        </body>
    </html>
  );
}
